# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: picpay-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: picpay
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: